source 'https://rubygems.org'

gem 'rails', '3.2.8'

gem 'mysql2'

gem 'json'
gem 'i18n', '0.6.11'

# Gems used only for assets and not required
# in production environments by default.
group :assets do
  gem 'sass-rails',   '~> 3.2.3'
  gem 'coffee-rails', '~> 3.2.0'

  gem 'uglifier', '>= 1.0.3'
end

# jquery plugin
gem 'jquery-rails'

# browser detection
gem 'browser'
